#!/sbin/sh
echo 1 > /sys/class/leds/button-backlight-portrait/currents 2> /dev/null
echo $2 > /sys/class/leds/button-backlight-portrait/currents 2> /dev/null
echo 1 > /sys/class/leds/button-backlight/currents 2> /dev/null
echo $2 > /sys/class/leds/button-backlight/currents 2> /dev/null

echo $2 > "/sys/class/leds/1;36mkeyboard-backlight/brightness" 2> /dev/null
echo $1 > "/sys/class/leds/1;36mkeyboard-backlight/brightness" 2> /dev/null

echo $2 > "/sys/class/leds/36mkeyboard-backlight/brightness" 2> /dev/null
echo $1 > "/sys/class/leds/36mkeyboard-backlight/brightness" 2> /dev/null

echo $2 > "/sys/class/leds/1;36mbutton-backlight/brightness" 2> /dev/null
echo $1 > "/sys/class/leds/1;36mbutton-backlight/brightness" 2> /dev/null

echo $2 > "/sys/class/leds/1;36mbutton-backlight/brightness" 2> /dev/null
echo $1 > "/sys/class/leds/1;36mbutton-backlight/brightness" 2> /dev/null

echo $2 > "/sys/class/leds/keyboard-backlight/brightness" 2> /dev/null
echo $1 > "/sys/class/leds/keyboard-backlight/brightness" 2> /dev/null

echo $2 > "/sys/class/leds/keyboard-backlight/brightness" 2> /dev/null
echo $1 > "/sys/class/leds/keyboard-backlight/brightness" 2> /dev/null

echo $2 > "/sys/class/leds/button-backlight/brightness" 2> /dev/null
echo $1 > "/sys/class/leds/button-backlight/brightness" 2> /dev/null

echo $2 > "/sys/class/leds/button-backlight/brightness" 2> /dev/null
echo $1 > "/sys/class/leds/button-backlight/brightness" 2> /dev/null

exit 0
